Added NSError for error during serialization
nodes-ios/Serializable pull request #132
Opened 2017-03-14 13:44 UTC by jakobmygind

Sometimes the responseSerializable method would never return. Returning an NSError seems to remedy this weirdness

2017-03-14 13:46 UTC, dominik-hadl commented on Serpent/Serpent/Classes/Extensions/AlamofireExtension.swift
> +                //                }
Please, don't leave commented out code in the codebase, unless necessary.

2017-04-05 08:58 UTC, chriscombs submitted a review, later dismissed

2017-04-05 09:03 UTC, chriscombs reviewed
Codecov is complaining about line 40 and 41. You might be able to test it by comparing the .failure value's userInfo to whatever the response should be.

2017-04-05 09:07 UTC, dominik-hadl requested changes

2017-04-05 09:07 UTC, nickskull commented on Serpent/Serpent/Classes/Extensions/AlamofireExtension.swift
> +            case .failure(_):
I think it would be nice to use the error provided here and also put it into the NSError that we return - more information is always better.

2017-04-05 12:21 UTC, dominik-hadl approved these changes

2017-04-05 12:26 UTC, chriscombs approved these changes

2017-04-05 12:27 UTC, merged